import assert from "node:assert/strict";
import test from "node:test";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runRepositoryOperation } from "../../src/session/checkpoints/repositoryOperation.js";
const execute = promisify(execFile);

test("Git operations honor the real index, literal filenames, unborn branches, stale staging and first push", async t => {
  const base = await mkdtemp(join(tmpdir(), "pilotdeck-git-")), workspace = join(base, "repo"), remote = join(base, "remote.git");
  await mkdir(workspace); t.after(() => rm(base, { recursive: true, force: true }));
  const git = async (...args: string[]) => (await execute("git", args, { cwd: workspace })).stdout.trim();
  await runRepositoryOperation(workspace, { operation: "init" });
  await git("config", "user.name", "Checkpoint QA"); await git("config", "user.email", "qa@example.test");
  const strange = process.platform === "win32" ? "[文件] with spaces.txt" : "[file] with\nnewline.txt";
  await writeFile(join(workspace, strange), "original\n"); await writeFile(join(workspace, "manual.txt"), "manual\n");
  await runRepositoryOperation(workspace, { operation: "stage", files: [strange] });
  await runRepositoryOperation(workspace, { operation: "unstage", files: [strange] });
  assert.equal(await git("ls-files"), ""); assert.equal(await readFile(join(workspace, strange), "utf8"), "original\n");
  await runRepositoryOperation(workspace, { operation: "stage", files: [strange] });
  const staleTree = await git("write-tree");
  await runRepositoryOperation(workspace, { operation: "stage", files: ["manual.txt"] });
  await assert.rejects(runRepositoryOperation(workspace, { operation: "commit", message: "stale", expectedIndexTree: staleTree }), { code: "INDEX_CHANGED" });
  await writeFile(join(workspace, strange), "unstaged newer text\n");
  await runRepositoryOperation(workspace, { operation: "commit", message: "first commit", expectedIndexTree: await git("write-tree") });
  assert.equal(await git("show", `HEAD:${strange}`), "original");
  assert.equal(await readFile(join(workspace, strange), "utf8"), "unstaged newer text\n");
  assert.equal(await git("show", "HEAD:manual.txt"), "manual");
  await assert.rejects(runRepositoryOperation(workspace, { operation: "stage", files: ["../outside"] }), { code: "INVALID_PATH" });
  await execute("git", ["init", "--bare", remote]); await git("remote", "add", "origin", remote);
  await runRepositoryOperation(workspace, { operation: "push" });
  assert.equal(await git("rev-parse", "@{upstream}"), await git("rev-parse", "HEAD"));
  await git("branch", "another-branch"); await git("config", "push.default", "matching");
  await runRepositoryOperation(workspace, { operation: "stage", files: [strange] });
  await runRepositoryOperation(workspace, { operation: "commit", message: "second commit", expectedIndexTree: await git("write-tree") });
  await runRepositoryOperation(workspace, { operation: "push" });
  assert.equal(await git("rev-parse", "@{upstream}"), await git("rev-parse", "HEAD"));
});
