import { app, BrowserWindow, dialog, ipcMain, Menu, shell } from "electron";
import { spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";

type ManagedProcess = {
  name: string;
  child: ChildProcess;
};

type RuntimeInfo = {
  serverPort: number;
  gatewayPort: number;
  runtimeRoot: string;
  logPath: string;
};

let mainWindow: BrowserWindow | null = null;
let runtime: RuntimeManager | null = null;
let isQuitting = false;

const APP_ID = "cn.pilotdeck.desktop";
const SENTINEL_API_KEY = "PLACEHOLDER_RUN_ONBOARDING_TO_REPLACE";

const DESKTOP_BOOTSTRAP_YAML = `# Auto-generated by PilotDeck Desktop.
# Open the Web UI to finish onboarding: choose a provider, paste an API key,
# and pick a model. The gateway boots with this placeholder config so the
# server can start, but apiKey="${SENTINEL_API_KEY}" tells the UI to show onboarding.
schemaVersion: 1
agent:
  model: _placeholder/_placeholder
model:
  providers:
    _placeholder:
      protocol: openai
      url: https://placeholder.invalid
      apiKey: ${SENTINEL_API_KEY}
      models:
        _placeholder:
          capabilities:
            maxOutputTokens: 16384
adapters:
  feishu:
    enabled: false
    appId: ""
    appSecret: ""
router:
  enabled: true
  scenarios:
    default: _placeholder/_placeholder
  fallback:
    default:
      - _placeholder/_placeholder
  zeroUsageRetry:
    enabled: true
    maxAttempts: 2
  tokenSaver:
    enabled: true
    judge: _placeholder/_placeholder
    defaultTier: medium
    judgeTimeoutMs: 15000
    tiers:
      simple:
        model: _placeholder/_placeholder
        description: "Simple greetings, confirmations, single-step Q&A, trivial file writes, remembering rules"
      medium:
        model: _placeholder/_placeholder
        description: "Single tool call, short text generation, 1-2 file read/write, code generation"
      complex:
        model: _placeholder/_placeholder
        description: "Needs sub-agent orchestration: parallel workstreams, delegation to specialized agents"
      reasoning:
        model: _placeholder/_placeholder
        description: "Deep single-agent work: multi-file operations, data analysis, multi-step workflows, web research, structured reports from many sources"
  autoOrchestrate:
    enabled: true
    triggerTiers:
      - complex
    slimSystemPrompt: true
    allowedTools:
      - agent
      - read_file
      - grep
      - glob
      - read_skill
    subagentMaxTokens: 48000
  stats:
    enabled: true
cron:
  enabled: true
  timezone: Asia/Shanghai
  maxConcurrentRuns: 2
`;

const OPTIONAL_CONFIG_PATCHES = [
  {
    key: "adapters",
    snippet: `\nadapters:\n  feishu:\n    enabled: false\n    appId: ""\n    appSecret: ""\n`,
  },
  {
    key: "cron",
    snippet: `\ncron:\n  enabled: true\n  timezone: Asia/Shanghai\n  maxConcurrentRuns: 2\n`,
  },
];

class RuntimeManager {
  private readonly processes: ManagedProcess[] = [];
  private readonly logPath: string;
  private logStream: fs.WriteStream | null = null;
  private info: RuntimeInfo | null = null;

  constructor(
    private readonly runtimeRoot: string,
    private readonly nodeBinary: string,
  ) {
    app.setAppLogsPath(path.join(app.getPath("userData"), "logs"));
    this.logPath = path.join(app.getPath("logs"), "runtime.log");
  }

  getInfo(): RuntimeInfo | null {
    return this.info;
  }

  async start(): Promise<RuntimeInfo> {
    fs.mkdirSync(path.dirname(this.logPath), { recursive: true });
    this.logStream = fs.createWriteStream(this.logPath, { flags: "a" });
    this.log(`PilotDeck Desktop runtime starting from ${this.runtimeRoot}`);
    const config = ensurePilotConfig((message) => this.log(message));

    const serverPort = await findFreePort(3001);
    const gatewayPort = await findFreePort(18789);
    const commonEnv = {
      ...process.env,
      HOST: "127.0.0.1",
      PILOT_HOME: config.pilotHome,
      PILOTDECK_CONFIG_DIR: config.pilotHome,
      SERVER_PORT: String(serverPort),
      PILOTDECK_GATEWAY_PORT: String(gatewayPort),
      PILOTDECK_GATEWAY_URL: `ws://127.0.0.1:${gatewayPort}/ws`,
      PILOTDECK_DESKTOP: "1",
      PILOTDECK_SKIP_BROWSER_OPEN: "1",
      PILOTDECK_SKIP_DEFAULT_PROJECT: "1",
    };

    const gateway = this.spawnRuntime("gateway", this.gatewayCommand(), this.runtimeRoot, commonEnv);
    await waitForPortOrProcessExit(gateway, "gateway", gatewayPort, "127.0.0.1", 90_000, this.logPath);

    const server = this.spawnRuntime(
      "server",
      [this.nodeBinary, "--import", "tsx", "server/index.js"],
      path.join(this.runtimeRoot, "ui"),
      commonEnv,
    );
    await waitForPortOrProcessExit(server, "server", serverPort, "127.0.0.1", 90_000, this.logPath);

    this.info = {
      serverPort,
      gatewayPort,
      runtimeRoot: this.runtimeRoot,
      logPath: this.logPath,
    };
    this.log(`PilotDeck Desktop runtime ready: http://127.0.0.1:${serverPort}`);
    return this.info;
  }

  async stop(): Promise<void> {
    for (const proc of [...this.processes].reverse()) {
      await killProcessTree(proc.child).catch((error) => {
        this.log(`Failed to stop ${proc.name}: ${String(error)}`);
      });
    }
    this.processes.length = 0;
    this.log("PilotDeck Desktop runtime stopped");
    this.logStream?.end();
    this.logStream = null;
  }

  private gatewayCommand(): string[] {
    const builtEntry = path.join(this.runtimeRoot, "dist", "src", "cli", "pilotdeck.js");
    if (fs.existsSync(builtEntry)) {
      return [this.nodeBinary, builtEntry, "server"];
    }
    return [this.nodeBinary, "--import", "tsx", path.join("src", "cli", "pilotdeck.ts"), "server"];
  }

  private spawnRuntime(
    name: string,
    command: string[],
    cwd: string,
    env: NodeJS.ProcessEnv,
  ): ChildProcess {
    const [bin, ...args] = command;
    if (!bin) throw new Error(`Missing command for ${name}`);
    const child = spawn(bin, args, {
      cwd,
      env,
      stdio: ["ignore", "pipe", "pipe"],
      detached: process.platform !== "win32",
    });
    this.processes.push({ name, child });
    this.log(`[${name}] spawn ${bin} ${args.join(" ")}`);

    child.stdout.on("data", (chunk: Buffer) => this.logChunk(name, chunk));
    child.stderr.on("data", (chunk: Buffer) => this.logChunk(name, chunk));
    child.on("exit", (code, signal) => {
      this.log(`[${name}] exited code=${code ?? "null"} signal=${signal ?? "null"}`);
      if (!isQuitting && this.info) {
        void dialog.showMessageBox({
          type: "error",
          title: "PilotDeck runtime stopped",
          message: `${name} exited unexpectedly. See runtime log for details.`,
          detail: this.logPath,
        });
      }
    });
    return child;
  }

  private logChunk(name: string, chunk: Buffer): void {
    const text = chunk.toString("utf8");
    for (const line of text.split(/\r?\n/)) {
      if (line.trim()) this.log(`[${name}] ${line}`);
    }
  }

  private log(message: string): void {
    const line = `${new Date().toISOString()} ${message}${os.EOL}`;
    this.logStream?.write(line);
    if (!app.isPackaged) process.stdout.write(line);
  }
}

async function createWindow(): Promise<void> {
  const runtimeRoot = resolveRuntimeRoot();
  const nodeBinary = resolveNodeBinary();
  runtime = new RuntimeManager(runtimeRoot, nodeBinary);
  const info = await runtime.start();
  const icon = resolveAppIcon();

  if (process.platform === "win32") {
    Menu.setApplicationMenu(null);
  }

  mainWindow = new BrowserWindow({
    width: 1320,
    height: 900,
    minWidth: 960,
    minHeight: 640,
    title: "PilotDeck",
    ...(icon ? { icon } : {}),
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: "deny" };
  });

  await mainWindow.loadURL(`http://127.0.0.1:${info.serverPort}`);
}

function resolveRuntimeRoot(): string {
  if (process.env.PILOTDECK_DESKTOP_RUNTIME_ROOT) {
    return path.resolve(process.env.PILOTDECK_DESKTOP_RUNTIME_ROOT);
  }
  if (app.isPackaged) {
    return path.join(process.resourcesPath, "runtime");
  }
  return path.resolve(__dirname, "..", "..", "..");
}

function resolveNodeBinary(): string {
  if (process.env.PILOTDECK_DESKTOP_NODE) {
    return process.env.PILOTDECK_DESKTOP_NODE;
  }
  if (!app.isPackaged) {
    return process.platform === "win32" ? "node.exe" : "node";
  }
  const binary = process.platform === "win32"
    ? path.join(process.resourcesPath, "node", "node.exe")
    : path.join(process.resourcesPath, "node", "bin", "node");
  if (!fs.existsSync(binary)) {
    throw new Error(`Bundled Node runtime not found: ${binary}`);
  }
  return binary;
}

function resolveAppIcon(): string | undefined {
  const fileName = process.platform === "win32" ? "icon.ico" : "icon.png";
  const iconPath = app.isPackaged
    ? path.join(process.resourcesPath, "icons", fileName)
    : path.resolve(__dirname, "..", "resources", "icons", fileName);
  return fs.existsSync(iconPath) ? iconPath : undefined;
}

function ensurePilotConfig(log: (message: string) => void): { pilotHome: string; configPath: string } {
  const pilotHome = process.env.PILOT_HOME
    ? path.resolve(process.env.PILOT_HOME)
    : path.join(os.homedir(), ".pilotdeck");
  const configPath = path.join(pilotHome, "pilotdeck.yaml");
  fs.mkdirSync(pilotHome, { recursive: true });

  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, DESKTOP_BOOTSTRAP_YAML, "utf8");
    log(`Created placeholder PilotDeck config at ${configPath}`);
    return { pilotHome, configPath };
  }

  const content = fs.readFileSync(configPath, "utf8");
  if (!hasTopLevelSection(content, "agent") || !hasTopLevelSection(content, "model")) {
    const backupPath = `${configPath}.backup-${new Date().toISOString().replace(/[:.]/g, "-")}`;
    fs.copyFileSync(configPath, backupPath);
    fs.writeFileSync(configPath, DESKTOP_BOOTSTRAP_YAML, "utf8");
    log(`Replaced invalid PilotDeck config at ${configPath}; backup saved to ${backupPath}`);
    return { pilotHome, configPath };
  }

  let nextContent = content;
  for (const patch of OPTIONAL_CONFIG_PATCHES) {
    if (!hasTopLevelSection(nextContent, patch.key)) {
      nextContent += patch.snippet;
    }
  }
  if (nextContent !== content) {
    fs.writeFileSync(configPath, nextContent, "utf8");
    log(`Patched missing optional PilotDeck config sections in ${configPath}`);
  }

  return { pilotHome, configPath };
}

function hasTopLevelSection(content: string, key: string): boolean {
  return new RegExp(`^${key}\\s*:`, "m").test(content);
}

function findFreePort(preferred: number): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.once("error", () => {
      const fallback = 20000 + Math.floor(Math.random() * 40000);
      findFreePort(fallback).then(resolve, reject);
    });
    server.once("listening", () => {
      const address = server.address();
      server.close(() => {
        resolve(typeof address === "object" && address ? address.port : preferred);
      });
    });
    server.listen(preferred, "127.0.0.1");
  });
}

function waitForPort(port: number, host: string, timeoutMs: number): Promise<void> {
  const startedAt = Date.now();
  return new Promise((resolve, reject) => {
    const attempt = () => {
      const socket = net.createConnection({ host, port });
      socket.once("connect", () => {
        socket.end();
        resolve();
      });
      socket.once("error", () => {
        socket.destroy();
        if (Date.now() - startedAt > timeoutMs) {
          reject(new Error(`Timed out waiting for ${host}:${port}`));
          return;
        }
        setTimeout(attempt, 250);
      });
    };
    attempt();
  });
}

function waitForPortOrProcessExit(
  child: ChildProcess,
  name: string,
  port: number,
  host: string,
  timeoutMs: number,
  logPath: string,
): Promise<void> {
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      child.off("exit", onExit);
      callback();
    };
    const onExit = (code: number | null, signal: NodeJS.Signals | null) => {
      finish(() => {
        reject(new Error(`${name} exited before it was ready (code=${code ?? "null"} signal=${signal ?? "null"}). See runtime log: ${logPath}`));
      });
    };
    child.once("exit", onExit);
    waitForPort(port, host, timeoutMs)
      .then(() => finish(resolve))
      .catch((error) => finish(() => reject(error)));
  });
}

function killProcessTree(child: ChildProcess): Promise<void> {
  if (child.exitCode !== null || child.killed) return Promise.resolve();
  return new Promise((resolve) => {
    child.once("exit", () => resolve());
    if (process.platform === "win32") {
      spawn("taskkill", ["/pid", String(child.pid), "/t", "/f"], { stdio: "ignore" })
        .once("exit", () => resolve());
      return;
    }
    if (child.pid) {
      try {
        process.kill(-child.pid, "SIGTERM");
      } catch {
        child.kill("SIGTERM");
      }
    }
    setTimeout(() => resolve(), 3000);
  });
}

ipcMain.handle("pilotdeck:get-runtime-info", () => runtime?.getInfo());

if (process.platform === "win32") {
  app.setAppUserModelId(APP_ID);
}

app.whenReady()
  .then(createWindow)
  .catch(async (error) => {
    const detail = error instanceof Error ? error.stack ?? error.message : String(error);
    await runtime?.stop().catch(() => undefined);
    dialog.showErrorBox("PilotDeck failed to start", detail);
    app.quit();
  });

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

app.on("before-quit", (event) => {
  isQuitting = true;
  if (!runtime) return;
  event.preventDefault();
  const currentRuntime = runtime;
  runtime = null;
  currentRuntime.stop().finally(() => app.exit(0));
});
