export {
  MODULE_PROTOCOL_VERSION,
  InProcessModuleAdapter,
  ModuleOperationHost,
  validateModuleMessage,
  type AgentExecutionContext,
  type ModelExecutionContext,
  type ModelInvokerPort,
  type ModuleBinding,
  type ModuleCapabilities,
  type ModuleCallRequest,
  type ModuleControlRequest,
  type ModuleError,
  type ModuleEvent,
  type ModuleExecuteProfile,
  type ModuleExecuteRequest,
  type ModuleHandshakeRequest,
  type HostCapabilityModuleMethod,
  type HostContextModuleMethod,
  type HostPermissionModuleMethod,
  type HostModuleCapabilities,
  type ModuleMessage,
  type ModuleMessageBase,
  type ModuleOperationSnapshot,
  type ModuleOperationState,
  type ModuleOutcome,
  type ModuleProtocolValidation,
  type ModuleResponse,
  type ModuleRetryability,
  type PreparedModelInvocation,
  type ToolPort,
  type InProcessModuleHandler,
  type InProcessModuleOptions,
} from "./protocol.js";
export { createRouterModelInvokerPort, createToolSchedulerPort } from "./adapters.js";
export {
  AgentLoopSidecarServer,
  createSidecarContextRuntime,
  createSidecarPorts,
  moduleOutcomeFromAgentResult,
  type AgentLoopSidecarOptions,
  type SidecarExecution,
  type SidecarExecutionFactory,
  type SidecarModuleCall,
  type SidecarModuleBinding,
  type SidecarModuleCallClient,
} from "./sidecar.js";
